In [1]:
import pandas as pd
import numpy as np

expert = pd.read_excel(r'/Users/huyennguyen/Documents/MDD/SQL/Data Files/ExpertReviewsClean43LIWC.xlsx')
expert.head()

,url,idvscore,reviewer,dateP,Rev,WC,Analytic,Clout,Authentic,Tone,...,Comma,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP
0,https://www.metacritic.com/movie/bronson,100.0,"""Andrew O'Hehir""",None,'Bronson owes a little or a lot to Kubrick s ...,25,73.88,11.52,6.70,25.77,...,4.00,0.00,0.0,0.0,0.0,0.00,0,8.00,0.0,0.0
1,https://www.metacritic.com/movie/bronson,90.0,'A.O. Scott',None,'Bronson invites you to admire its protagonis...,30,13.07,97.69,1.00,99.00,...,6.67,0.00,0.0,0.0,0.0,0.00,0,6.67,0.0,0.0
2,https://www.metacritic.com/movie/bronson,90.0,None,None,'Whether it s Peterson/Bronson s more theatri...,40,72.69,77.33,7.84,2.89,...,7.50,0.00,0.0,0.0,0.0,12.50,0,5.00,0.0,2.5
3,https://www.metacritic.com/movie/bronson,83.0,'Noel Murray',None,'There are two Bronsons on display here: the ...,39,65.46,99.00,1.00,25.77,...,5.13,2.56,0.0,0.0,0.0,0.00,0,5.13,0.0,0.0
4,https://www.metacritic.com/movie/bronson,80.0,'Joshua Rothkopf',None,'Refn has somehow found his way to an authent...,24,88.46,89.42,1.79,25.77,...,8.33,0.00,0.0,0.0,0.0,4.17,0,8.33,0.0,0.0

# 1. Checking Data Types

In [2]:
expert.info()
expert.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238973 entries, 0 to 238972
Data columns (total 98 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   url           238973 non-null  object
 1   idvscore      238971 non-null  float64
 2   reviewer      238971 non-null  object
 3   dateP         238971 non-null  object
 4   Rev           238971 non-null  object
 5   WC            238973 non-null  int64
 6   Analytic      238973 non-null  float64
 7   Clout         238973 non-null  float64
 8   Authentic     238973 non-null  float64
 9   Tone          238973 non-null  float64
 10  WPS           238973 non-null  float64
 11  Sixltr        238973 non-null  float64
 12  Dic           238973 non-null  float64
 13  function      238973 non-null  float64
 14  pronoun       238973 non-null  float64
 15  ppron         238973 non-null  float64
 16  i             238973 non-null  float64
 17  we            238973 non-null  float64
 18  you           238973 non-null  float64
 19  shehe         238973 non-null  float64
 20  they          238973 non-null  float64
 21  ipron         238973 non-null  float64
 22  article       238973 non-null  float64
 23  prep          238973 non-null  float64
 24  auxverb       238973 non-null  float64
 25  adverb        238973 non-null  float64
 26  conj          238973 non-null  float64
 27  negate        238973 non-null  float64
 28  verb          238973 non-null  float64
 29  adj           238973 non-null  float64
 30  compare       238973 non-null  float64
 31  interrog      238973 non-null  float64
 32  number        238973 non-null  float64
 33  quant         238973 non-null  float64
 34  affect        238973 non-null  float64
 35  posemo        238973 non-null  float64
 36  negemo        238973 non-null  float64
 37  anx           238973 non-null  float64
 38  anger         238973 non-null  float64
 39  sad           238973 non-null  float64
 40  social        238973 non-null  float64
 41  family        238973 non-null  float64
 42  friend        238973 non-null  float64
 43  female        238973 non-null  float64
 44  male          238973 non-null  float64
 45  cogproc       238973 non-null  float64
 46  insight       238973 non-null  float64
 47  cause         238973 non-null  float64
 48  discrep       238973 non-null  float64
 49  tentat        238973 non-null  float64
 50  certain       238973 non-null  float64
 51  differ        238973 non-null  float64
 52  percept       238973 non-null  float64
 53  see           238973 non-null  float64
 54  hear          238973 non-null  float64
 55  feel          238973 non-null  float64
 56  bio           238973 non-null  float64
 57  body          238973 non-null  float64
 58  health        238973 non-null  float64
 59  sexual        238973 non-null  float64
 60  ingest        238973 non-null  float64
 61  drives        238973 non-null  float64
 62  affiliation   238973 non-null  float64
 63  achieve       238973 non-null  float64
 64  power         238973 non-null  float64
 65  reward        238973 non-null  float64
 66  risk          238973 non-null  float64
 67  focuspast     238973 non-null  float64
 68  focuspresent  238973 non-null  float64
 69  focusfuture   238973 non-null  float64
 70  relativ       238973 non-null  float64
 71  motion        238973 non-null  float64
 72  space         238973 non-null  float64
 73  time          238973 non-null  float64
 74  work          238973 non-null  float64
 75  leisure       238973 non-null  float64
 76  home          238973 non-null  float64
 77  money         238973 non-null  float64
 78  relig         238973 non-null  float64
 79  death         238973 non-null  float64
 80  informal      238973 non-null  float64
 81  swear         238973 non-null  float64
 82  netspeak      238973 non-null  float64
 83  assent        238973 non-null  float64
 84  nonflu        238973 non-null  float64
 85  filler        238973 non-null  float64
 86  AllPunc       238973 non-null  float64
 87  Period        238973 non-null  float64
 88  Comma         238973 non-null  float64
 89  Colon         238973 non-null  float64
 90  SemiC         238973 non-null  float64
 91  QMark         238973 non-null  float64
 92  Exclam        238973 non-null  float64
 93  Dash          238973 non-null  float64
 94  Quote         238973 non-null  int64
 95  Apostro       238973 non-null  float64
 96  Parenth       238973 non-null  float64
 97  OtherP        238973 non-null  float64
dtypes: float64(92), int64(2), object(4)
memory usage: 178.7+ MB

,idvscore,WC,Analytic,Clout,Authentic,Tone,WPS,Sixltr,Dic,function,...,Comma,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP
count,238971.000000,238973.000000,238973.000000,238973.000000,238973.000000,238973.000000,238973.000000,238973.000000,238973.000000,238973.000000,...,238973.000000,238973.000000,238973.000000,238973.000000,238973.000000,238973.000000,238973.0,238973.000000,238973.000000,238973.000000
mean,62.718359,28.023999,80.168282,54.302440,24.771660,54.507723,21.730619,23.839279,76.253142,44.352281,...,5.586475,0.178399,0.091125,0.081441,0.031984,2.365231,0.0,13.629909,0.351170,0.071266
std,20.752696,14.012528,25.291018,24.302338,29.204285,39.862789,10.716071,11.809405,11.524903,12.524273,...,5.068776,0.865741,0.608532,0.714153,0.618102,4.349331,0.0,28.025998,1.627782,0.694356
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
25%,50.000000,18.000000,72.690000,38.740000,1.520000,25.770000,14.330000,16.670000,69.700000,37.840000,...,2.170000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,5.410000,0.000000,0.000000
50%,63.000000,27.000000,93.260000,50.000000,11.000000,58.390000,20.000000,23.080000,76.920000,44.120000,...,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,7.410000,0.000000,0.000000
75%,78.000000,37.000000,98.080000,72.470000,39.760000,98.870000,28.000000,30.000000,83.330000,50.000000,...,8.000000,0.000000,0.000000,0.000000,0.000000,3.570000,0.0,11.110000,0.000000,0.000000
max,100.000000,133.000000,99.000000,99.000000,99.000000,99.000000,92.000000,100.000000,100.000000,100.000000,...,80.000000,25.000000,25.000000,50.000000,100.000000,100.000000,0.0,200.000000,50.000000,75.000000

# Shape 

238,973 rows x 98 columns

# Duplicate Rows

In [3]:
print("Duplicate Rows:", expert.duplicated().sum())

Duplicate Rows: 27

In [4]:
before = len(expert)
expert = expert.drop_duplicates().reset_index(drop=True)
print(f"Removed {before - len(expert)} rows; {len(expert)} remain")

Removed 27 rows; 238946 remain

In [5]:
print("Duplicate Rows:", expert.duplicated().sum())

Duplicate Rows: 0

# NaN Values

In [6]:
na = expert.isna().sum()
na[na > 0] #instead of 98 lines we get a short list of only the columns with missing values

idvscore    2
reviewer    2
dateP       2
Rev         2
dtype: int64

In [7]:
expert[expert.isna().any(axis=1)] #which rows have NaN values?

,url,idvscore,reviewer,dateP,Rev,WC,Analytic,Clout,Authentic,Tone,...,Comma,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP
41662,https://www.metacritic.com/movie/whiteout,NaN,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0
157744,https://www.metacritic.com/movie/micmac---au-f...,NaN,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0

In [8]:
expert = expert.dropna(subset=['idvscore', 'reviewer', 'dateP', 'Rev'])

In [9]:
expert = expert.reset_index(drop=True)
print("Real NaN values left:", expert.isna().sum().sum())
print("Rows:", len(expert))

Real NaN values left: 0
Rows: 238944

# Find Hidden Missing Values e.g "None"
### Pandas can't tell that the text "None" means missing, so it counts "None" as a real reviewer name or date

In [10]:
text_cols = expert.select_dtypes(include=['object']).columns
placeholders = ['', 'nan', 'none', 'null', 'n/a', 'na', '-', '?']

for col in text_cols:
    s = expert[col].astype(str).str.strip().str.strip("'\"").str.strip().str.lower()
    found = s[s.isin(placeholders)].value_counts()
    if len(found):
        print(col, found.to_dict())

reviewer {'none': 25207}
dateP {'none': 104470}
Rev {'none': 4555, '': 1}

In [11]:
for col in ['reviewer', 'dateP', 'Rev']:
    s = expert[col].astype(str).str.strip().str.strip("'\"").str.strip().str.lower()
    expert.loc[s.isin(['none', '']), col] = np.nan

In [12]:
expert[['reviewer', 'dateP', 'Rev']].isna().sum()

reviewer     25207
dateP       104470
Rev           4556
dtype: int64

In [13]:
print("Total rows:", len(expert))
(expert[['reviewer', 'dateP', 'Rev']].isna().mean() * 100).round(1)
#In words, "For each of the three columns, what percentage of cells are blank?"

Total rows: 238944

reviewer    10.5
dateP       43.7
Rev          1.9
dtype: float64

# Data Types

In [14]:
expert['idvscore'] = expert['idvscore'].astype(int)

In [15]:
expert.info()
expert.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238944 entries, 0 to 238943
Data columns (total 98 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   url           238944 non-null  object
 1   idvscore      238944 non-null  int64
 2   reviewer      213737 non-null  object
 3   dateP         134474 non-null  object
 4   Rev           234388 non-null  object
 5   WC            238944 non-null  int64
 6   Analytic      238944 non-null  float64
 7   Clout         238944 non-null  float64
 8   Authentic     238944 non-null  float64
 9   Tone          238944 non-null  float64
 10  WPS           238944 non-null  float64
 11  Sixltr        238944 non-null  float64
 12  Dic           238944 non-null  float64
 13  function      238944 non-null  float64
 14  pronoun       238944 non-null  float64
 15  ppron         238944 non-null  float64
 16  i             238944 non-null  float64
 17  we            238944 non-null  float64
 18  you           238944 non-null  float64
 19  shehe         238944 non-null  float64
 20  they          238944 non-null  float64
 21  ipron         238944 non-null  float64
 22  article       238944 non-null  float64
 23  prep          238944 non-null  float64
 24  auxverb       238944 non-null  float64
 25  adverb        238944 non-null  float64
 26  conj          238944 non-null  float64
 27  negate        238944 non-null  float64
 28  verb          238944 non-null  float64
 29  adj           238944 non-null  float64
 30  compare       238944 non-null  float64
 31  interrog      238944 non-null  float64
 32  number        238944 non-null  float64
 33  quant         238944 non-null  float64
 34  affect        238944 non-null  float64
 35  posemo        238944 non-null  float64
 36  negemo        238944 non-null  float64
 37  anx           238944 non-null  float64
 38  anger         238944 non-null  float64
 39  sad           238944 non-null  float64
 40  social        238944 non-null  float64
 41  family        238944 non-null  float64
 42  friend        238944 non-null  float64
 43  female        238944 non-null  float64
 44  male          238944 non-null  float64
 45  cogproc       238944 non-null  float64
 46  insight       238944 non-null  float64
 47  cause         238944 non-null  float64
 48  discrep       238944 non-null  float64
 49  tentat        238944 non-null  float64
 50  certain       238944 non-null  float64
 51  differ        238944 non-null  float64
 52  percept       238944 non-null  float64
 53  see           238944 non-null  float64
 54  hear          238944 non-null  float64
 55  feel          238944 non-null  float64
 56  bio           238944 non-null  float64
 57  body          238944 non-null  float64
 58  health        238944 non-null  float64
 59  sexual        238944 non-null  float64
 60  ingest        238944 non-null  float64
 61  drives        238944 non-null  float64
 62  affiliation   238944 non-null  float64
 63  achieve       238944 non-null  float64
 64  power         238944 non-null  float64
 65  reward        238944 non-null  float64
 66  risk          238944 non-null  float64
 67  focuspast     238944 non-null  float64
 68  focuspresent  238944 non-null  float64
 69  focusfuture   238944 non-null  float64
 70  relativ       238944 non-null  float64
 71  motion        238944 non-null  float64
 72  space         238944 non-null  float64
 73  time          238944 non-null  float64
 74  work          238944 non-null  float64
 75  leisure       238944 non-null  float64
 76  home          238944 non-null  float64
 77  money         238944 non-null  float64
 78  relig         238944 non-null  float64
 79  death         238944 non-null  float64
 80  informal      238944 non-null  float64
 81  swear         238944 non-null  float64
 82  netspeak      238944 non-null  float64
 83  assent        238944 non-null  float64
 84  nonflu        238944 non-null  float64
 85  filler        238944 non-null  float64
 86  AllPunc       238944 non-null  float64
 87  Period        238944 non-null  float64
 88  Comma         238944 non-null  float64
 89  Colon         238944 non-null  float64
 90  SemiC         238944 non-null  float64
 91  QMark         238944 non-null  float64
 92  Exclam        238944 non-null  float64
 93  Dash          238944 non-null  float64
 94  Quote         238944 non-null  int64
 95  Apostro       238944 non-null  float64
 96  Parenth       238944 non-null  float64
 97  OtherP        238944 non-null  float64
dtypes: float64(91), int64(3), object(4)
memory usage: 178.7+ MB

url          object
idvscore      int64
reviewer     object
dateP        object
Rev          object
             ...
Dash        float64
Quote         int64
Apostro     float64
Parenth     float64
OtherP      float64
Length: 98, dtype: object

### Dates

In [16]:
expert['dateP'].dropna().sample(10, random_state=1)
#see what the dates look like, while skipping the blanks.

131297     'Sep 24, 2013'
81651       'Feb 3, 2016'
83781      'Apr 14, 2016'
73374       'Mar 8, 2018'
56463      'Sep 11, 2019'
121112     'Sep 29, 2016'
11497      'Jan 18, 2018'
59386      'Dec 20, 2019'
115895      'Jul 4, 2017'
114444     'May 31, 2017'
Name: dateP, dtype: object

### It's the same thing we saw with 'None' in Rev: the quote marks are part of the text. We need to remove them first, or pandas won't recognise the dates.

In [17]:
expert['dateP'] = pd.to_datetime(
    expert['dateP'].str.strip().str.strip("'"),
    format='%b %d, %Y'
)

In [18]:
print(expert['dateP'].isna().sum())
expert['dateP'].dtype

104470

dtype('<M8[ns]')

In [19]:
expert.head()

,url,idvscore,reviewer,dateP,Rev,WC,Analytic,Clout,Authentic,Tone,...,Comma,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP
0,https://www.metacritic.com/movie/bronson,100,"""Andrew O'Hehir""",NaT,'Bronson owes a little or a lot to Kubrick s ...,25,73.88,11.52,6.70,25.77,...,4.00,0.00,0.0,0.0,0.0,0.00,0,8.00,0.0,0.0
1,https://www.metacritic.com/movie/bronson,90,'A.O. Scott',NaT,'Bronson invites you to admire its protagonis...,30,13.07,97.69,1.00,99.00,...,6.67,0.00,0.0,0.0,0.0,0.00,0,6.67,0.0,0.0
2,https://www.metacritic.com/movie/bronson,90,NaN,NaT,'Whether it s Peterson/Bronson s more theatri...,40,72.69,77.33,7.84,2.89,...,7.50,0.00,0.0,0.0,0.0,12.50,0,5.00,0.0,2.5
3,https://www.metacritic.com/movie/bronson,83,'Noel Murray',NaT,'There are two Bronsons on display here: the ...,39,65.46,99.00,1.00,25.77,...,5.13,2.56,0.0,0.0,0.0,0.00,0,5.13,0.0,0.0
4,https://www.metacritic.com/movie/bronson,80,'Joshua Rothkopf',NaT,'Refn has somehow found his way to an authent...,24,88.46,89.42,1.79,25.77,...,8.33,0.00,0.0,0.0,0.0,4.17,0,8.33,0.0,0.0

### Everything is looking good , but reviewer and Rev columns still have quotes and stuff, so we have to clean that up.

In [20]:
for col in ['reviewer', 'Rev']:
    expert[col] = (
        expert[col]
        .str.strip()
        .str.replace(r"(?s)^(['\"])(.*)\1$", r"\2", regex=True)
    )

In [21]:
for col in ['reviewer', 'Rev']:
    print(col, expert[col].str.match(r"^['\"]").sum())

reviewer 0
Rev 0

In [22]:
expert.head(3)

,url,idvscore,reviewer,dateP,Rev,WC,Analytic,Clout,Authentic,Tone,...,Comma,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP
0,https://www.metacritic.com/movie/bronson,100,Andrew O'Hehir,NaT,Bronson owes a little or a lot to Kubrick s Cl...,25,73.88,11.52,6.70,25.77,...,4.00,0.0,0.0,0.0,0.0,0.0,0,8.00,0.0,0.0
1,https://www.metacritic.com/movie/bronson,90,A.O. Scott,NaT,Bronson invites you to admire its protagonist ...,30,13.07,97.69,1.00,99.00,...,6.67,0.0,0.0,0.0,0.0,0.0,0,6.67,0.0,0.0
2,https://www.metacritic.com/movie/bronson,90,NaN,NaT,Whether it s Peterson/Bronson s more theatrica...,40,72.69,77.33,7.84,2.89,...,7.50,0.0,0.0,0.0,0.0,12.5,0,5.00,0.0,2.5

### Extract Title

In [23]:
# Extract the title slug from the URL and turn dashes into spaces
expert["title_from_url"] = (
    expert["url"]
    .str.extract(r"/movie/([^/?#]+)", expand=False)
    .str.replace("-", " ", regex=False)
)

# Some slugs end with a "(YYYY)" year tag -> strip it off
expert["title"] = (
    expert["title_from_url"]
    .str.replace(r"\s*\(\d{4}\)$", "", regex=True)
    .str.strip()
)

# Drop the helper column
expert = expert.drop(columns=["title_from_url"])

# Normalize casing/spacing so titles compare and group consistently
expert["title"] = expert["title"].str.lower().str.strip()

print("Missing titles remaining:", expert["title"].isna().sum())
print("Remaining mojibake in title:", expert["title"].str.contains("©", na=False).sum())

Missing titles remaining: 0
Remaining mojibake in title: 0

In [24]:
# move 'title' right after 'reviewer'
cols = [c for c in expert.columns if c != 'title']
cols.insert(cols.index('reviewer') + 1, 'title')
expert = expert[cols]

# rows with a reviewer first, empty reviewers at the bottom
empty = expert['reviewer'].isna() | expert['reviewer'].astype(str).str.strip().str.lower().isin(['', 'none', 'nan'])
expert = expert.sort_values('reviewer', key=lambda _: empty, kind='stable').reset_index(drop=True)

expert[['reviewer', 'title']].head()

           reviewer    title
0    Andrew O'Hehir  bronson
1        A.O. Scott  bronson
2       Noel Murray  bronson
3   Joshua Rothkopf  bronson
4  Bill Goodykoontz  bronson

In [25]:
# surrogate key: unique sequential id for each review, placed as the first column
expert.insert(0, 'id_expert_review', range(1, len(expert) + 1))

print("Unique ids:", expert['id_expert_review'].is_unique)
expert.head(3)

Unique ids: True

,id_expert_review,url,idvscore,reviewer,title,dateP,Rev,WC,Analytic,Clout,...,Comma,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP
0,1,https://www.metacritic.com/movie/bronson,100,Andrew O'Hehir,bronson,NaT,Bronson owes a little or a lot to Kubrick s Cl...,25,73.88,11.52,...,4.00,0.00,0.0,0.0,0.0,0.0,0,8.00,0.0,0.0
1,2,https://www.metacritic.com/movie/bronson,90,A.O. Scott,bronson,NaT,Bronson invites you to admire its protagonist ...,30,13.07,97.69,...,6.67,0.00,0.0,0.0,0.0,0.0,0,6.67,0.0,0.0
2,3,https://www.metacritic.com/movie/bronson,83,Noel Murray,bronson,NaT,There are two Bronsons on display here: the im...,39,65.46,99.00,...,5.13,2.56,0.0,0.0,0.0,0.0,0,5.13,0.0,0.0

In [ ]:
#with pd.ExcelWriter('expert_cleaned.xlsx', datetime_format='yyyy-mm-dd') as writer:
 #   expert.to_excel(writer, sheet_name='expert', index=False)

#print("Saved:", expert.shape)

Saved: (238944, 100)

In [27]:
#check = pd.read_excel('expert_cleaned.xlsx')
#print("Shape:", check.shape)
#print(check.dtypes[['idvscore', 'reviewer', 'dateP', 'Rev']])
#check[['reviewer', 'dateP', 'Rev']].isna().sum()