In [10]:
import pandas as pd
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [11]:
sales = pd.read_excel(r"C:\Users\user\Documents\UNI DDB\Database m,anagement\Data Files\sales.xlsx")

In [16]:
sales.head()

,year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,Unnamed: 8,opening_weekend,theatre_count,avg run per theatre,runtime,keywords,creative_type,url
0,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...
1,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,NaN,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust
2,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos
3,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...
4,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,NaN,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...

In [17]:
sales.tail()

,year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,Unnamed: 8,opening_weekend,theatre_count,avg run per theatre,runtime,keywords,creative_type,url
30607,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,12356.0,NaN,NaN,NaN,NaN,NaN,168.0,NaN,Factual,https://www.the-numbers.com/movie/Jokbeoldu-si...
30608,2021,March 5th,My Salinger Year,Drama,914119.0,54730.0,968849.0,NaN,NaN,28851.0,123.0,2.0,101.0,Set in New York City,Contemporary Fiction,https://www.the-numbers.com/movie/My-Salinger-...
30609,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,240000.0,NaN,NaN,NaN,NaN,NaN,85.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Escort-Vehic...
30610,2021,May 21st,The Dry,Thriller/Suspense,16987526.0,364397.0,17351923.0,NaN,NaN,119364.0,186.0,2.5,118.0,Crime Thriller,Contemporary Fiction,https://www.the-numbers.com/movie/Dry-The-(Aus...
30611,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,33396899.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Super Hero,https://www.the-numbers.com/movie/Posledniy-bo...

In [18]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 30612 entries, 0 to 30611
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   year                      30612 non-null  int64
 1   release_date              30612 non-null  str
 2   title                     30604 non-null  object
 3   genre                     28908 non-null  str
 4   international_box_office  21575 non-null  float64
 5   domestic_box_office       11884 non-null  float64
 6   worldwide_box_office      21575 non-null  float64
 7   production_budget         4480 non-null   float64
 8   Unnamed: 8                0 non-null      float64
 9   opening_weekend           10929 non-null  float64
 10  theatre_count             10963 non-null  float64
 11  avg run per theatre       10952 non-null  float64
 12  runtime                   24559 non-null  float64
 13  keywords                  12517 non-null  object
 14  creative_type             26667 non-null  str
 15  url                       30612 non-null  str
dtypes: float64(9), int64(1), object(2), str(4)
memory usage: 3.7+ MB

In [21]:
sales.describe()

,year,international_box_office,domestic_box_office,worldwide_box_office,production_budget,Unnamed: 8,opening_weekend,theatre_count,avg run per theatre,runtime
count,30612.000000,2.157500e+04,1.188400e+04,2.157500e+04,4.480000e+03,0.0,1.092900e+04,10963.000000,10952.000000,24559.000000
mean,2014.542108,1.586202e+07,1.735331e+07,2.524796e+07,3.642238e+07,NaN,5.488562e+06,723.147040,4.124562,101.502993
std,5.525085,6.659680e+07,5.050972e+07,1.009796e+08,4.644049e+07,NaN,1.633207e+07,1246.401636,3.423855,27.194334
min,2000.000000,2.000000e+00,2.000000e+01,2.000000e+00,1.100000e+03,NaN,1.100000e+01,1.000000,0.000000,11.000000
25%,2012.000000,2.637500e+04,2.986550e+04,3.422900e+04,6.500000e+06,NaN,7.352000e+03,2.000000,2.000000,89.000000
50%,2016.000000,3.348470e+05,2.587510e+05,4.753220e+05,2.000000e+07,NaN,4.087500e+04,8.000000,3.400000,97.000000
75%,2019.000000,4.282312e+06,7.667212e+06,6.302152e+06,4.500000e+07,NaN,2.150979e+06,969.500000,5.400000,110.000000
max,2021.000000,2.085392e+09,9.366622e+08,2.845900e+09,4.000000e+08,NaN,3.571150e+08,4725.000000,88.400000,2020.000000

In [27]:
sales.round()

,year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,Unnamed: 8,opening_weekend,theatre_count,avg run per theatre,runtime,keywords,creative_type,url
0,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...
1,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,NaN,5486209.0,2433.0,3.0,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust
2,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos
3,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...
4,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,NaN,12177488.0,2411.0,5.0,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30607,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,12356.0,NaN,NaN,NaN,NaN,NaN,168.0,NaN,Factual,https://www.the-numbers.com/movie/Jokbeoldu-si...
30608,2021,March 5th,My Salinger Year,Drama,914119.0,54730.0,968849.0,NaN,NaN,28851.0,123.0,2.0,101.0,Set in New York City,Contemporary Fiction,https://www.the-numbers.com/movie/My-Salinger-...
30609,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,240000.0,NaN,NaN,NaN,NaN,NaN,85.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Escort-Vehic...
30610,2021,May 21st,The Dry,Thriller/Suspense,16987526.0,364397.0,17351923.0,NaN,NaN,119364.0,186.0,2.0,118.0,Crime Thriller,Contemporary Fiction,https://www.the-numbers.com/movie/Dry-The-(Aus...
30611,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,33396899.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Super Hero,https://www.the-numbers.com/movie/Posledniy-bo...

In [24]:
sales.columns

Index(['year', 'release_date', 'title', 'genre', 'international_box_office',
       'domestic_box_office', 'worldwide_box_office', 'production_budget',
       'Unnamed: 8', 'opening_weekend', 'theatre_count', 'avg run per theatre',
       'runtime', 'keywords', 'creative_type', 'url'],
      dtype='str')

In [29]:
sales.shape

(30612, 16)

In [30]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 30612 entries, 0 to 30611
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   year                      30612 non-null  int64
 1   release_date              30612 non-null  str
 2   title                     30604 non-null  object
 3   genre                     28908 non-null  str
 4   international_box_office  21575 non-null  float64
 5   domestic_box_office       11884 non-null  float64
 6   worldwide_box_office      21575 non-null  float64
 7   production_budget         4480 non-null   float64
 8   Unnamed: 8                0 non-null      float64
 9   opening_weekend           10929 non-null  float64
 10  theatre_count             10963 non-null  float64
 11  avg run per theatre       10952 non-null  float64
 12  runtime                   24559 non-null  float64
 13  keywords                  12517 non-null  object
 14  creative_type             26667 non-null  str
 15  url                       30612 non-null  str
dtypes: float64(9), int64(1), object(2), str(4)
memory usage: 3.7+ MB

In [31]:
sales.isnull().sum()

year                            0
release_date                    0
title                           8
genre                        1704
international_box_office     9037
domestic_box_office         18728
worldwide_box_office         9037
production_budget           26132
Unnamed: 8                  30612
opening_weekend             19683
theatre_count               19649
avg run per theatre         19660
runtime                      6053
keywords                    18095
creative_type                3945
url                             0
dtype: int64

In [36]:
sales.isnull().sum()/len(sales)*100

year                          0.000000
release_date                  0.000000
title                         0.026134
genre                         5.566445
international_box_office     29.521103
domestic_box_office          61.178623
worldwide_box_office         29.521103
production_budget            85.365216
Unnamed: 8                  100.000000
opening_weekend              64.298314
theatre_count                64.187247
avg run per theatre          64.223180
runtime                      19.773292
keywords                     59.110806
creative_type                12.887103
url                           0.000000
dtype: float64

In [34]:
#dataprofiling 
missing_data_percantage = (
    sales.isnull().mean()*100 
    ).round(2)

missing_data_percantage

year                          0.00
release_date                  0.00
title                         0.03
genre                         5.57
international_box_office     29.52
domestic_box_office          61.18
worldwide_box_office         29.52
production_budget            85.37
Unnamed: 8                  100.00
opening_weekend              64.30
theatre_count                64.19
avg run per theatre          64.22
runtime                      19.77
keywords                     59.11
creative_type                12.89
url                           0.00
dtype: float64

In [40]:
sales.duplicated().shape

(30612,)

In [41]:
sales.columns=(
    sales.columns
    .str.strip()
    .str.lower()
    .str.replace(" ","_")
)

In [42]:
sales.columns

Index(['year', 'release_date', 'title', 'genre', 'international_box_office',
       'domestic_box_office', 'worldwide_box_office', 'production_budget',
       'unnamed:_8', 'opening_weekend', 'theatre_count', 'avg_run_per_theatre',
       'runtime', 'keywords', 'creative_type', 'url'],
      dtype='str')

In [43]:
sales = sales.dropna(axis=1 , how='all')

In [44]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 30612 entries, 0 to 30611
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   year                      30612 non-null  int64
 1   release_date              30612 non-null  str
 2   title                     30604 non-null  object
 3   genre                     28908 non-null  str
 4   international_box_office  21575 non-null  float64
 5   domestic_box_office       11884 non-null  float64
 6   worldwide_box_office      21575 non-null  float64
 7   production_budget         4480 non-null   float64
 8   opening_weekend           10929 non-null  float64
 9   theatre_count             10963 non-null  float64
 10  avg_run_per_theatre       10952 non-null  float64
 11  runtime                   24559 non-null  float64
 12  keywords                  12517 non-null  object
 13  creative_type             26667 non-null  str
 14  url                       30612 non-null  str
dtypes: float64(8), int64(1), object(2), str(4)
memory usage: 3.5+ MB

In [45]:
sales.columns

Index(['year', 'release_date', 'title', 'genre', 'international_box_office',
       'domestic_box_office', 'worldwide_box_office', 'production_budget',
       'opening_weekend', 'theatre_count', 'avg_run_per_theatre', 'runtime',
       'keywords', 'creative_type', 'url'],
      dtype='str')

In [46]:
sales.shape

(30612, 15)

In [50]:
text_columns = sales.select_dtypes(include="object").columns               #Remove unneseccory space

for column in text_columns:
    sales[column] = sales[column].str.strip()

C:\Users\user\AppData\Local\Temp\ipykernel_8424\893145005.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = sales.select_dtypes(include="object").columns               #Remove unneseccory space

In [49]:
sales.tail()

,year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg_run_per_theatre,runtime,keywords,creative_type,url
30607,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,12356.0,NaN,NaN,NaN,NaN,168.0,NaN,Factual,https://www.the-numbers.com/movie/Jokbeoldu-si...
30608,2021,March 5th,My Salinger Year,Drama,914119.0,54730.0,968849.0,NaN,28851.0,123.0,2.0,101.0,Set in New York City,Contemporary Fiction,https://www.the-numbers.com/movie/My-Salinger-...
30609,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,240000.0,NaN,NaN,NaN,NaN,85.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Escort-Vehic...
30610,2021,May 21st,The Dry,Thriller/Suspense,16987526.0,364397.0,17351923.0,NaN,119364.0,186.0,2.5,118.0,Crime Thriller,Contemporary Fiction,https://www.the-numbers.com/movie/Dry-The-(Aus...
30611,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,33396899.0,NaN,NaN,NaN,NaN,NaN,NaN,Super Hero,https://www.the-numbers.com/movie/Posledniy-bo...

In [53]:
import numpy as np

sales = sales.replace(r"^\s*$", np.nan, regex=True)

In [55]:
sales.duplicated().sum()

np.int64(0)

In [57]:
sales.duplicated(
    subset=["title","year"]
).sum()

np.int64(90)

In [58]:
sales[sales["title"].isnull()]

,year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg_run_per_theatre,runtime,keywords,creative_type,url
14,2008,February 15th,NaN,Drama,1334204.0,NaN,1334204.0,NaN,NaN,NaN,NaN,114.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/120-(Turkey)
566,2018,November 30th,NaN,Thriller/Suspense,6871135.0,NaN,6871135.0,NaN,NaN,NaN,NaN,148.0,NaN,Science Fiction,https://www.the-numbers.com/movie/2-0-(India)(...
1248,2016,December 9th,NaN,Documentary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.0,Musicians,Factual,https://www.the-numbers.com/movie/808-(2016)
1571,2017,November 3rd,NaN,Documentary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.0,Political Campaign,Factual,https://www.the-numbers.com/movie/11-8-16
1753,2018,October 26th,NaN,Drama,34710.0,NaN,34710.0,NaN,NaN,NaN,NaN,85.0,Closeted Homosexual,Historical Fiction,https://www.the-numbers.com/movie/1985-(2018)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29083,2021,June 25th,NaN,Drama,78477113.0,NaN,78477113.0,NaN,NaN,NaN,NaN,137.0,NaN,Dramatization,https://www.the-numbers.com/movie/1921-(2021-C...
29389,2020,January 16th,NaN,Romantic Comedy,8060952.0,NaN,8060952.0,NaN,NaN,NaN,NaN,92.0,NaN,Science Fiction,https://www.the-numbers.com/movie/(NE)-Idealny...
29395,2020,January 14th,NaN,Drama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.0,Robot,Science Fiction,https://www.the-numbers.com/movie/2050-(2019)
29863,2021,May 20th,NaN,Drama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/1986-(2021-G...
30552,2021,January 19th,NaN,Drama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/1982-(Lebanon)

In [59]:
sales.loc[
    sales["title"].isnull(),
    ["year", "release_date", "url"]
]

       year   release_date                                                url
14     2008  February 15th     https://www.the-numbers.com/movie/120-(Turkey)
566    2018  November 30th  https://www.the-numbers.com/movie/2-0-(India)(...
1248   2016   December 9th       https://www.the-numbers.com/movie/808-(2016)
1571   2017   November 3rd          https://www.the-numbers.com/movie/11-8-16
1753   2018   October 26th      https://www.the-numbers.com/movie/1985-(2018)
...     ...            ...                                                ...
29083  2021      June 25th  https://www.the-numbers.com/movie/1921-(2021-C...
29389  2020   January 16th  https://www.the-numbers.com/movie/(NE)-Idealny...
29395  2020   January 14th      https://www.the-numbers.com/movie/2050-(2019)
29863  2021       May 20th  https://www.the-numbers.com/movie/1986-(2021-G...
30552  2021   January 19th   https://www.the-numbers.com/movie/1982-(Lebanon)

[78 rows x 3 columns]

In [60]:
sales["title_from_url"] = (
    sales["url"]
    .str.extract(r"/movie/([^/?#]+)", expand=False)
    .str.replace("-", " ", regex=False)
)

sales.loc[
    sales["title"].isnull(),
    ["title", "title_from_url", "year", "release_date", "url"]
].head(20)

,title,title_from_url,year,release_date,url
14,NaN,120 (Turkey),2008,February 15th,https://www.the-numbers.com/movie/120-(Turkey)
566,NaN,2 0 (India)(2018),2018,November 30th,https://www.the-numbers.com/movie/2-0-(India)(...
1248,NaN,808 (2016),2016,December 9th,https://www.the-numbers.com/movie/808-(2016)
1571,NaN,11 8 16,2017,November 3rd,https://www.the-numbers.com/movie/11-8-16
1753,NaN,1985 (2018),2018,October 26th,https://www.the-numbers.com/movie/1985-(2018)
1845,NaN,1945 (Hungary),2017,November 1st,https://www.the-numbers.com/movie/1945-(Hungary)
2302,NaN,22 July (2018) (U S Film),2018,October 10th,https://www.the-numbers.com/movie/22-July-(201...
2510,NaN,96 (India)(2018),2018,October 5th,https://www.the-numbers.com/movie/96-(India)(2...
2836,NaN,3 4 (Bulgaria) (2018),2018,September 28th,https://www.the-numbers.com/movie/3-4-(Bulgari...
2894,NaN,Muchenik (Russia),2016,April 14th,https://www.the-numbers.com/movie/Muchenik-(Ru...
3353,NaN,37 (2016),2016,October 7th,https://www.the-numbers.com/movie/37-(2016)
3987,NaN,9 11,2017,September 8th,https://www.the-numbers.com/movie/9-11
4201,NaN,31 (2016),2016,September 1st,https://www.the-numbers.com/movie/31-(2016)
4440,NaN,51 por ciento (Argentina) (2017),2017,August 25th,https://www.the-numbers.com/movie/51-por-cient...
5045,NaN,1991 (Canada) (2018),2018,July 27th,https://www.the-numbers.com/movie/1991-(Canada...
5179,NaN,(T)ERROR (2015),2015,October 7th,https://www.the-numbers.com/movie/(T)ERROR-(2015)
5231,NaN,303 (Germany) (2018),2018,July 19th,https://www.the-numbers.com/movie/303-(Germany...
5957,NaN,3688 (Singapore),2015,September 17th,https://www.the-numbers.com/movie/3688-(Singap...
6187,NaN,2 22 (2017),2017,June 30th,https://www.the-numbers.com/movie/2-22-(2017)
6323,NaN,1944,2016,July 1st,https://www.the-numbers.com/movie/1944

In [61]:
sales["title_clean"] = (
    sales["title_from_url"]
    .str.replace(r"\s*\(\d{4}\)$", "", regex=True)
    .str.strip()
)

In [62]:
sales.loc[
    sales["title"].isnull(),
    ["title_from_url", "title_clean", "year"]
]

,title_from_url,title_clean,year
14,120 (Turkey),120 (Turkey),2008
566,2 0 (India)(2018),2 0 (India),2018
1248,808 (2016),808,2016
1571,11 8 16,11 8 16,2017
1753,1985 (2018),1985,2018
...,...,...,...
29083,1921 (2021 China),1921 (2021 China),2021
29389,(NE) Idealnyy muzhchina (Russia),(NE) Idealnyy muzhchina (Russia),2020
29395,2050 (2019),2050,2020
29863,1986 (2021 Germany),1986 (2021 Germany),2021
30552,1982 (Lebanon),1982 (Lebanon),2021

In [63]:
missing_titles = sales.loc[
    sales["title"].isnull(),
    ["title_clean", "year"]
]

missing_titles[missing_titles.duplicated(keep=False)]

Empty DataFrame
Columns: [title_clean, year]
Index: []

In [64]:
sales.loc[
    sales["title"].isnull(),
    ["title_from_url", "title_clean", "year"]
].head(30)

                        title_from_url                      title_clean  year
14                        120 (Turkey)                     120 (Turkey)  2008
566                  2 0 (India)(2018)                      2 0 (India)  2018
1248                        808 (2016)                              808  2016
1571                           11 8 16                          11 8 16  2017
1753                       1985 (2018)                             1985  2018
1845                    1945 (Hungary)                   1945 (Hungary)  2017
2302         22 July (2018) (U S Film)        22 July (2018) (U S Film)  2018
2510                  96 (India)(2018)                       96 (India)  2018
2836             3 4 (Bulgaria) (2018)                   3 4 (Bulgaria)  2018
2894                 Muchenik (Russia)                Muchenik (Russia)  2016
3353                         37 (2016)                               37  2016
3987                              9 11                             9 11  2017
4201                         31 (2016)                               31  2016
4440  51 por ciento (Argentina) (2017)        51 por ciento (Argentina)  2017
5045              1991 (Canada) (2018)                    1991 (Canada)  2018
5179                   (T)ERROR (2015)                         (T)ERROR  2015
5231              303 (Germany) (2018)                    303 (Germany)  2018
5957                  3688 (Singapore)                 3688 (Singapore)  2015
6187                       2 22 (2017)                             2 22  2017
6323                              1944                             1944  2016
6505                        211 (2018)                              211  2018
6979                       11 (Turkey)                      11 (Turkey)  2017
6981                              1155                             1155  2017
7287           1965 (Singapore) (2015)                 1965 (Singapore)  2015
7780                     20 16 (China)                    20 16 (China)  2017
8148                 24 (India) (2016)                       24 (India)  2016
8498            25 April (New Zealand)           25 April (New Zealand)  2016
9426   DisHonesty The Truth About Lies  DisHonesty The Truth About Lies  2015
9719                   12 12 12 (2013)                         12 12 12  2013
9801               91 1(Turkey) (2016)                     91 1(Turkey)  2016

In [65]:
pd.set_option("display.max_rows", 100)

sales.loc[
    sales["title"].isnull(),
    ["title_from_url", "title_clean", "year"]
]

,title_from_url,title_clean,year
14,120 (Turkey),120 (Turkey),2008
566,2 0 (India)(2018),2 0 (India),2018
1248,808 (2016),808,2016
1571,11 8 16,11 8 16,2017
1753,1985 (2018),1985,2018
1845,1945 (Hungary),1945 (Hungary),2017
2302,22 July (2018) (U S Film),22 July (2018) (U S Film),2018
2510,96 (India)(2018),96 (India),2018
2836,3 4 (Bulgaria) (2018),3 4 (Bulgaria),2018
2894,Muchenik (Russia),Muchenik (Russia),2016
3353,37 (2016),37,2016
3987,9 11,9 11,2017
4201,31 (2016),31,2016
4440,51 por ciento (Argentina) (2017),51 por ciento (Argentina),2017
5045,1991 (Canada) (2018),1991 (Canada),2018
5179,(T)ERROR (2015),(T)ERROR,2015
5231,303 (Germany) (2018),303 (Germany),2018
5957,3688 (Singapore),3688 (Singapore),2015
6187,2 22 (2017),2 22,2017
6323,1944,1944,2016
6505,211 (2018),211,2018
6979,11 (Turkey),11 (Turkey),2017
6981,1155,1155,2017
7287,1965 (Singapore) (2015),1965 (Singapore),2015
7780,20 16 (China),20 16 (China),2017
8148,24 (India) (2016),24 (India),2016
8498,25 April (New Zealand),25 April (New Zealand),2016
9426,DisHonesty The Truth About Lies,DisHonesty The Truth About Lies,2015
9719,12 12 12 (2013),12 12 12,2013
9801,91 1(Turkey) (2016),91 1(Turkey),2016
10801,11 11 11,11 11 11,2011
10995,13,13,2011
11211,Plus One,Plus One,2013
11271,1915,1915,2015
11322,1 54 (Canada),1 54 (Canada),2018
12209,3 (DREI),3 (DREI),2011
13032,7500,7500,2014
13305,11 4 08,11 4 08,2010
13530,2012,2012,2009
13836,(Untitled),(Untitled),2009
15044,9,9,2009
15170,360,360,2012
15323,1981,1981,2009
15811,42 (2013),42,2013
16479,500 Days of Summer,500 Days of Summer,2009
16680,1921 (India),1921 (India),2018
17224,9 99,9 99,2009
17503,2046,2046,2004
18651,21 (2008),21,2008
18872,1408,1408,2007
19242,11 14,11 14,2005
19408,45365,45365,2010
20009,12 (2009 Russian Federation),12 (2009 Russian Federation),2009
21171,4,4,2006
21187,300 (2007),300,2007
21231,15,15,2005
22671,1917 (2019),1917,2019
23014,3022,3022,2019
23652,(Nie)znajomi (Poland),(Nie)znajomi (Poland),2019
24152,2020 (2020 Spain),2020 (2020 Spain),2020
25074,7500 (Germany) (2019),7500 (Germany),2019
25179,915 (2020),915,2020
25388,2067 (2020 Australia),2067 (2020 Australia),2020
25797,(R)Evolutie (2021 Netherlands),(R)Evolutie (2021 Netherlands),2021
25988,3 19 (2021 Italy),3 19 (2021 Italy),2021
26609,2040 (Oz)(2019),2040 (Oz),2019
26864,100 (India)(2019),100 (India),2019
26875,99 (India)(2019),99 (India),2019
27699,8 Sekiz (2021 Turkey),8 Sekiz (2021 Turkey),2021
27724,8 (South Africa),8 (South Africa),2020
27956,499 (Mexico),499 (Mexico),2021
28235,6 45 (2021),6 45,2021
28825,118 (India)(2019),118 (India),2019
29083,1921 (2021 China),1921 (2021 China),2021
29389,(NE) Idealnyy muzhchina (Russia),(NE) Idealnyy muzhchina (Russia),2020
29395,2050 (2019),2050,2020
29863,1986 (2021 Germany),1986 (2021 Germany),2021
30552,1982 (Lebanon),1982 (Lebanon),2021

In [66]:
sales[
    sales["title"].notnull()
][["title", "year"]].head()

                 title  year
0         Bakha Satang  2000
1            Antitrust  2001
2             Santitos  2000
3  Frank McKlusky C.I.  2002
4   A Walk to Remember  2002

In [67]:
existing_titles = sales.loc[
    sales["title"].notnull(),
    ["title", "year"]
].copy()

existing_titles["title_compare"] = (
    existing_titles["title"]
    .astype(str)
    .str.strip()
    .str.lower()
)

missing_titles = sales.loc[
    sales["title"].isnull(),
    ["title_clean", "year"]
].copy()

missing_titles["title_compare"] = (
    missing_titles["title_clean"]
    .astype(str)
    .str.strip()
    .str.lower()
)

matches = missing_titles.merge(
    existing_titles,
    on=["title_compare", "year"],
    how="inner"
)

matches

Empty DataFrame
Columns: [title_clean, year, title_compare, title]
Index: []

In [68]:
sales.loc[
    sales["title"].isnull(),
    "title"
] = sales.loc[
    sales["title"].isnull(),
    "title_clean"
]

In [69]:
sales["title"].isnull().sum()

np.int64(0)

In [70]:
sales[["title", "year", "url"]].head(20)

,title,year,url
0,Bakha Satang,2000,https://www.the-numbers.com/movie/Bakha-Satang...
1,Antitrust,2001,https://www.the-numbers.com/movie/Antitrust
2,Santitos,2000,https://www.the-numbers.com/movie/Santitos
3,Frank McKlusky C.I.,2002,https://www.the-numbers.com/movie/Frank-McKlus...
4,A Walk to Remember,2002,https://www.the-numbers.com/movie/Walk-to-Reme...
5,Zig Zag,2002,https://www.the-numbers.com/movie/Zig-Zag
6,TakhtÃƒÂ© siah,2002,https://www.the-numbers.com/movie/Takhte-siah
7,"Angry Monk: Reflections on Tibet, The",2009,https://www.the-numbers.com/movie/Angry-Monk-R...
8,30 Years to Life,2002,https://www.the-numbers.com/movie/30-Years-to-...
9,The Killing of John Lennon,2008,https://www.the-numbers.com/movie/Killing-of-J...
10,Mad Money,2008,https://www.the-numbers.com/movie/Mad-Money
11,Little Chenier,2008,https://www.the-numbers.com/movie/Little-Chenier
12,Over Her Dead Body,2008,https://www.the-numbers.com/movie/Over-Her-Dea...
13,O Ano em Que Meus Pais SaÃƒÂ­ram de FÃƒÂ©rias,2008,https://www.the-numbers.com/movie/Ano-em-Que-M...
14,120 (Turkey),2008,https://www.the-numbers.com/movie/120-(Turkey)
15,The Other Boleyn Girl,2008,https://www.the-numbers.com/movie/Other-Boleyn...
16,A Lawyer Walks into a Bar,2008,https://www.the-numbers.com/movie/Lawyer-Walks...
17,La Rondine,2008,https://www.the-numbers.com/movie/Rondine-La
18,Jodaeiye Nader az Simin,2011,https://www.the-numbers.com/movie/Jodaeiye-Nad...
19,Pariah,2011,https://www.the-numbers.com/movie/Pariah-(2011)

In [72]:
sales = sales.drop(
    columns=["title_from_url", "title_clean"]
)

In [73]:
sales["title_clean"] = (
    sales["title"]
    .str.lower()
    .str.strip()
)

In [74]:
sales["encoding_issue"] = (
    sales["title"]
    .astype(str)
    .str.contains("Ã|Â|â", regex=True)
)

In [75]:
sales["encoding_issue"].value_counts()

encoding_issue
False    27976
True      2636
Name: count, dtype: int64

In [76]:
sales["release_date_original"] = sales["release_date"]

In [77]:
sales["release_date_temp"] = (
    sales["release_date"]
    .str.replace(
        r"(\d+)(st|nd|rd|th)",
        r"\1",
        regex=True
    )
)

In [78]:
sales["release_date_clean"] = pd.to_datetime(
    sales["release_date_temp"]
    + " "
    + sales["year"].astype(str),
    errors="coerce"
)

In [79]:
sales["release_date_clean"].isnull().sum()

np.int64(46)

In [80]:
sales.loc[
    sales["release_date_clean"].isnull(),
    ["year", "release_date_original", "title"]
]

,year,release_date_original,title
3,2002,2002 (Wide) by,Frank McKlusky C.I.
679,2016,2016 (Limited) by,Stage V
680,2016,2016 (Limited) by,No Beast So Fierce
4255,2017,August,Sand and Blood
7990,2015,Spring,11 minut
8254,2016,April,Unseen
8582,2012,December,Yelling to the Sky
8995,2017,Week of April 13th,Ma-li-an-neu-wa Ma-ga-let
10979,2011,October,Chillerama
11552,2008,2008 (Wide) by,Le renard et l'enfant
11553,2008,2008 (Wide) by,Steppin: The Movie
11555,2008,2008 (Limited),The Jesus Guy
11557,2008,2008 (Wide) by,Spring Breakdown
11840,2013,August,Oxygen for the Ears: Living Jazz
11845,2013,August,Breath of the Gods
12221,2010,2010 (Limited) by,Poppies: Odyssey Of An Opium Eater
12271,2013,2013 (Limited) by,"Syngue sabour, pierre de patience"
13989,2015,February,Mr. Kaplan
16193,2006,October,The Alibi
17167,2004,July,In My Father's Den
17549,2008,April,One Fast Move or IÃ¢â‚¬â„¢m Gone: KerouacÃ¢â‚¬...
17630,2010,April,The Wildest Dream
21324,2002,May,Until Morning
22200,2003,2003 (Wide),To End All Wars
22332,2003,2003 (Limited),The Last Minute
22456,2002,2002 (Wide),Wise Girls
23662,2020,2020 (Wide) (,La rivoluzione siamo noi
23669,2020,2020 (Canceled) by,Chasing Whiskey
23690,2019,Fall 2020 (Canceled) by,Monsoon
24226,2020,2020 (Canceled) by,Run
24407,2020,2022 (Wide) by,The Comeback Trail
24735,2021,2021 (Wide) (,Broken Keys
24842,2020,2020 (Canceled) by,Mosul
25441,2020,2020 (Canceled) by,Saint Maud
25954,2019,2020 (Canceled) by,KaijÃƒÂ» no kodomo
26040,2020,2020 (Canceled) by,Mulan
26685,2020,Fall 2020 (Canceled) by,Greenland
26696,2020,2020 (Canceled) by,The Secret: Dare to Dream
27424,2021,July,Shika No Ou
28367,2021,2020 (Canceled) by,Stillwater
28381,2019,May,Fisherman's Friends
29082,2021,December,I Carry You With Me
29403,2021,Summer,Gyokou no Nikuko-chan
30319,2021,2022 (Canceled) by,El olvido que seremos
30410,2021,2021 (Canceled) by,Extinct
30555,2021,2021 (Canceled) by,Wish Dragon

In [81]:
sales = sales.drop(columns=["release_date_temp"])

In [82]:
sales[
    [
        "international_box_office",
        "domestic_box_office",
        "worldwide_box_office",
        "production_budget",
        "opening_weekend",
        "theatre_count",
        "avg_run_per_theatre",
        "runtime"
    ]
].describe()

,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg_run_per_theatre,runtime
count,2.157500e+04,1.188400e+04,2.157500e+04,4.480000e+03,1.092900e+04,10963.000000,10952.000000,24559.000000
mean,1.586202e+07,1.735331e+07,2.524796e+07,3.642238e+07,5.488562e+06,723.147040,4.124562,101.502993
std,6.659680e+07,5.050972e+07,1.009796e+08,4.644049e+07,1.633207e+07,1246.401636,3.423855,27.194334
min,2.000000e+00,2.000000e+01,2.000000e+00,1.100000e+03,1.100000e+01,1.000000,0.000000,11.000000
25%,2.637500e+04,2.986550e+04,3.422900e+04,6.500000e+06,7.352000e+03,2.000000,2.000000,89.000000
50%,3.348470e+05,2.587510e+05,4.753220e+05,2.000000e+07,4.087500e+04,8.000000,3.400000,97.000000
75%,4.282312e+06,7.667212e+06,6.302152e+06,4.500000e+07,2.150979e+06,969.500000,5.400000,110.000000
max,2.085392e+09,9.366622e+08,2.845900e+09,4.000000e+08,3.571150e+08,4725.000000,88.400000,2020.000000

In [83]:
numeric_columns = [
    "international_box_office",
    "domestic_box_office",
    "worldwide_box_office",
    "production_budget",
    "opening_weekend",
    "theatre_count",
    "avg_run_per_theatre",
    "runtime"
]

for column in numeric_columns:
    print(
        column,
        (sales[column] < 0).sum()
    )

international_box_office 0
domestic_box_office 0
worldwide_box_office 0
production_budget 0
opening_weekend 0
theatre_count 0
avg_run_per_theatre 0
runtime 0

In [84]:
sales.sort_values(
    "runtime",
    ascending=False
)[["title", "runtime"]].head(20)

                                           title  runtime
27957       Barbara Lee: Speaking Truth to Power   2020.0
7179                                    Amazonia    983.0
16350                           AmÃ…Â¾inai kartu    980.0
24691                                    La Flor    803.0
3431                                Meesterspion    770.0
3427                      Out 1, noli me tangere    760.0
28613                         The Works and Days    480.0
22311                        The Cremaster Cycle    398.0
21828                      La meglio gioventÃƒÂ¹    366.0
1608              Royal Opera House: Die Walkure    350.0
14346                                 La commune    345.0
3359                    Homeland: Iraq Year Zero    334.0
13452                          2018 Oscar Shorts    328.0
3145                          River of Fundament    319.0
18436                         The Pusher Trilogy    318.0
20057                  The Weathered Underground    310.0
835                Opera De Paris: Les Huguenots    300.0
1412   League Of Legends World Championship 2018    300.0
27899                     Met Opera: Die Walkure    295.0
3244         Tristan und Isolde - Met Opera 2016    287.0

In [85]:
sales["runtime_outlier"] = sales["runtime"] > 400

In [86]:
sales[
    sales["runtime_outlier"]
][["title", "year", "runtime", "url"]]

,title,year,runtime,url
3427,"Out 1, noli me tangere",2015,760.0,https://www.the-numbers.com/movie/Out-1-noli-m...
3431,Meesterspion,2016,770.0,https://www.the-numbers.com/movie/Meesterspion...
7179,Amazonia,2015,983.0,https://www.the-numbers.com/movie/Amazonia-(Br...
16350,AmÃ…Â¾inai kartu,2017,980.0,https://www.the-numbers.com/movie/Amzinai-kart...
24691,La Flor,2019,803.0,https://www.the-numbers.com/movie/Flor-La-(Arg...
27957,Barbara Lee: Speaking Truth to Power,2021,2020.0,https://www.the-numbers.com/movie/Barbara-Lee-...
28613,The Works and Days,2021,480.0,https://www.the-numbers.com/movie/Works-and-Da...

In [87]:
sales["production_budget"].fillna(0)

0               0.0
1        30000000.0
2               0.0
3               0.0
4        11000000.0
            ...
30607           0.0
30608           0.0
30609           0.0
30610           0.0
30611           0.0
Name: production_budget, Length: 30612, dtype: float64

In [88]:
sales["genre"].value_counts(dropna=False)

genre
Drama                  9218
Documentary            4683
Comedy                 4551
Thriller/Suspense      2281
Adventure              1999
Action                 1872
NaN                    1704
Horror                 1630
Romantic Comedy        1177
Concert/Performance     711
Musical                 268
Black Comedy            245
Multiple Genres         159
Western                 105
Educational               5
Reality                   4
Name: count, dtype: int64

In [89]:
sales["creative_type"].value_counts(dropna=False)

creative_type
Contemporary Fiction       14617
Factual                     4875
NaN                         3945
Historical Fiction          2106
Dramatization               1470
Kids Fiction                1195
Fantasy                     1127
Science Fiction             1051
Super Hero                   120
Multiple Creative Types      106
Name: count, dtype: int64

In [90]:
sales["url"].isnull().sum()

np.int64(0)

In [91]:
sales["url"].duplicated().sum()

np.int64(0)

In [92]:
sales = sales.reset_index(drop=True)

sales.insert(
    0,
    "sales_id",
    range(1, len(sales) + 1)
)

In [93]:
sales.head()

,sales_id,year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,...,avg_run_per_theatre,runtime,keywords,creative_type,url,title_clean,encoding_issue,release_date_original,release_date_clean,runtime_outlier
0,1,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,...,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...,bakha satang,False,January 1st,2000-01-01,False
1,2,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,...,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust,antitrust,False,January 12th,2001-01-12,False
2,3,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,...,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos,santitos,False,January 28th,2000-01-28,False
3,4,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,frank mcklusky c.i.,False,2002 (Wide) by,NaT,False
4,5,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,...,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...,a walk to remember,False,January 25th,2002-01-25,False

In [94]:
print("Rows and columns:")
print(sales.shape)

print("\nDuplicate rows:")
print(sales.duplicated().sum())

print("\nMissing values:")
print(sales.isnull().sum())

print("\nData types:")
print(sales.dtypes)

Rows and columns:
(30612, 21)

Duplicate rows:
0

Missing values:
sales_id                        0
year                            0
release_date                    0
title                           0
genre                        1704
international_box_office     9037
domestic_box_office         18728
worldwide_box_office         9037
production_budget           26132
opening_weekend             19683
theatre_count               19649
avg_run_per_theatre         19660
runtime                      6053
keywords                    18103
creative_type                3945
url                             0
title_clean                     0
encoding_issue                  0
release_date_original           0
release_date_clean             46
runtime_outlier                 0
dtype: int64

Data types:
sales_id                             int64
year                                 int64
release_date                           str
title                               object
genre                                  str
international_box_office           float64
domestic_box_office                float64
worldwide_box_office               float64
production_budget                  float64
opening_weekend                    float64
theatre_count                      float64
avg_run_per_theatre                float64
runtime                            float64
keywords                            object
creative_type                          str
url                                    str
title_clean                         object
encoding_issue                        bool
release_date_original                  str
release_date_clean          datetime64[us]
runtime_outlier                       bool
dtype: object

In [95]:
sales.head()

,sales_id,year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,...,avg_run_per_theatre,runtime,keywords,creative_type,url,title_clean,encoding_issue,release_date_original,release_date_clean,runtime_outlier
0,1,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,...,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...,bakha satang,False,January 1st,2000-01-01,False
1,2,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,...,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust,antitrust,False,January 12th,2001-01-12,False
2,3,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,...,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos,santitos,False,January 28th,2000-01-28,False
3,4,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,frank mcklusky c.i.,False,2002 (Wide) by,NaT,False
4,5,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,...,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...,a walk to remember,False,January 25th,2002-01-25,False

In [97]:
sales.shape

(30612, 21)

In [98]:
sales.columns.tolist()

['sales_id',
 'year',
 'release_date',
 'title',
 'genre',
 'international_box_office',
 'domestic_box_office',
 'worldwide_box_office',
 'production_budget',
 'opening_weekend',
 'theatre_count',
 'avg_run_per_theatre',
 'runtime',
 'keywords',
 'creative_type',
 'url',
 'title_clean',
 'encoding_issue',
 'release_date_original',
 'release_date_clean',
 'runtime_outlier']

In [99]:
sales.duplicated().sum()

np.int64(0)

In [100]:
sales.isnull().sum()

sales_id                        0
year                            0
release_date                    0
title                           0
genre                        1704
international_box_office     9037
domestic_box_office         18728
worldwide_box_office         9037
production_budget           26132
opening_weekend             19683
theatre_count               19649
avg_run_per_theatre         19660
runtime                      6053
keywords                    18103
creative_type                3945
url                             0
title_clean                     0
encoding_issue                  0
release_date_original           0
release_date_clean             46
runtime_outlier                 0
dtype: int64

In [102]:
sales.isnull().sum()/len(sales)*100

sales_id                     0.000000
year                         0.000000
release_date                 0.000000
title                        0.000000
genre                        5.566445
international_box_office    29.521103
domestic_box_office         61.178623
worldwide_box_office        29.521103
production_budget           85.365216
opening_weekend             64.298314
theatre_count               64.187247
avg_run_per_theatre         64.223180
runtime                     19.773292
keywords                    59.136940
creative_type               12.887103
url                          0.000000
title_clean                  0.000000
encoding_issue               0.000000
release_date_original        0.000000
release_date_clean           0.150268
runtime_outlier              0.000000
dtype: float64

In [103]:
sales["sales_id"].head(10)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: sales_id, dtype: int64

In [104]:
sales["sales_id"].is_unique

True

In [105]:
sales[
    ["title", "title_clean"]
].head(10)

,title,title_clean
0,Bakha Satang,bakha satang
1,Antitrust,antitrust
2,Santitos,santitos
3,Frank McKlusky C.I.,frank mcklusky c.i.
4,A Walk to Remember,a walk to remember
5,Zig Zag,zig zag
6,TakhtÃƒÂ© siah,takhtãƒâ© siah
7,"Angry Monk: Reflections on Tibet, The","angry monk: reflections on tibet, the"
8,30 Years to Life,30 years to life
9,The Killing of John Lennon,the killing of john lennon

In [106]:
sales["encoding_issue"].value_counts()

encoding_issue
False    27976
True      2636
Name: count, dtype: int64

In [107]:
sales.loc[
    sales["encoding_issue"] == True,
    ["title", "url"]
].head(20)

,title,url
6,TakhtÃƒÂ© siah,https://www.the-numbers.com/movie/Takhte-siah
13,O Ano em Que Meus Pais SaÃƒÂ­ram de FÃƒÂ©rias,https://www.the-numbers.com/movie/Ano-em-Que-M...
30,Minuscule - La vallÃƒÂ©e des fourmis perdues,https://www.the-numbers.com/movie/Minuscule-La...
47,"Boca Juniors 3D, la pelÃƒÂ­cula",https://www.the-numbers.com/movie/Boca-Juniors...
60,HÃƒÂ¢monÃƒÂ®,https://www.the-numbers.com/movie/Hamoni
68,Desu nÃƒÂ´to: Light Up the New World,https://www.the-numbers.com/movie/Desu-noto-Li...
78,Nuo Lietuvos nepabÃ„â€”gsi,https://www.the-numbers.com/movie/Nuo-Lietuvos...
81,PÃƒÂ¨re fils thÃƒÂ©rapie!,https://www.the-numbers.com/movie/Pere-fils-th...
83,Doktor Martin: ZÃƒÂ¡hada v Beskydech,https://www.the-numbers.com/movie/Doktor-Marti...
90,Tiempo despuÃƒÂ©s,https://www.the-numbers.com/movie/Tiempo-despu...
93,Tarp mÃ…Â«sÃ…Â³ mergaiÃ„ï¿½iÃ…Â³,https://www.the-numbers.com/movie/Tarp-musu-me...
94,TrileÃƒÂ§e,https://www.the-numbers.com/movie/Trilece-(Tur...
98,MÃƒÂ¼saadenizle BÃƒÂ¼yÃƒÂ¼kler,https://www.the-numbers.com/movie/Musaadenizle...
111,BÃƒÂ¶rÃƒÂ¼,https://www.the-numbers.com/movie/Boru-(Turkey...
116,Un violent dÃƒÂ©sir de bonheur,https://www.the-numbers.com/movie/Violent-desi...
121,L'homme fidÃƒÂ¨le,https://www.the-numbers.com/movie/homme-fidele...
126,YanÃ„Â±mda Kal,https://www.the-numbers.com/movie/Yanimda-Kal-...
130,Kamen RaidÃƒÂ¢ Heisei JenerÃƒÂªshonzu FoebÃƒÂ¢,https://www.the-numbers.com/movie/Kamen-Raida-...
141,SÃƒÂ¼kut Evi,https://www.the-numbers.com/movie/Sukut-Evi-(T...
149,Kurtlar ve Ãƒâ€¡akallar,https://www.the-numbers.com/movie/Kurtlar-ve-C...

In [108]:
sales[
    [
        "year",
        "release_date_original",
        "release_date_clean"
    ]
].head(20)

    year release_date_original release_date_clean
0   2000           January 1st         2000-01-01
1   2001          January 12th         2001-01-12
2   2000          January 28th         2000-01-28
3   2002        2002 (Wide) by                NaT
4   2002          January 25th         2002-01-25
5   2002             June 21st         2002-06-21
6   2002              May 10th         2002-05-10
7   2009           January 2nd         2009-01-02
8   2002              June 7th         2002-06-07
9   2008           January 2nd         2008-01-02
10  2008          January 18th         2008-01-18
11  2008          January 18th         2008-01-18
12  2008          February 1st         2008-02-01
13  2008         February 15th         2008-02-15
14  2008         February 15th         2008-02-15
15  2008         February 29th         2008-02-29
16  2008         February 29th         2008-02-29
17  2008             March 8th         2008-03-08
18  2011         December 30th         2011-12-30
19  2011         December 28th         2011-12-28

In [109]:
sales["release_date_clean"].isnull().sum()

np.int64(46)

In [110]:
sales.loc[
    sales["release_date_clean"].isnull(),
    [
        "year",
        "release_date_original",
        "title"
    ]
].head(50)

,year,release_date_original,title
3,2002,2002 (Wide) by,Frank McKlusky C.I.
679,2016,2016 (Limited) by,Stage V
680,2016,2016 (Limited) by,No Beast So Fierce
4255,2017,August,Sand and Blood
7990,2015,Spring,11 minut
8254,2016,April,Unseen
8582,2012,December,Yelling to the Sky
8995,2017,Week of April 13th,Ma-li-an-neu-wa Ma-ga-let
10979,2011,October,Chillerama
11552,2008,2008 (Wide) by,Le renard et l'enfant
11553,2008,2008 (Wide) by,Steppin: The Movie
11555,2008,2008 (Limited),The Jesus Guy
11557,2008,2008 (Wide) by,Spring Breakdown
11840,2013,August,Oxygen for the Ears: Living Jazz
11845,2013,August,Breath of the Gods
12221,2010,2010 (Limited) by,Poppies: Odyssey Of An Opium Eater
12271,2013,2013 (Limited) by,"Syngue sabour, pierre de patience"
13989,2015,February,Mr. Kaplan
16193,2006,October,The Alibi
17167,2004,July,In My Father's Den
17549,2008,April,One Fast Move or IÃ¢â‚¬â„¢m Gone: KerouacÃ¢â‚¬...
17630,2010,April,The Wildest Dream
21324,2002,May,Until Morning
22200,2003,2003 (Wide),To End All Wars
22332,2003,2003 (Limited),The Last Minute
22456,2002,2002 (Wide),Wise Girls
23662,2020,2020 (Wide) (,La rivoluzione siamo noi
23669,2020,2020 (Canceled) by,Chasing Whiskey
23690,2019,Fall 2020 (Canceled) by,Monsoon
24226,2020,2020 (Canceled) by,Run
24407,2020,2022 (Wide) by,The Comeback Trail
24735,2021,2021 (Wide) (,Broken Keys
24842,2020,2020 (Canceled) by,Mosul
25441,2020,2020 (Canceled) by,Saint Maud
25954,2019,2020 (Canceled) by,KaijÃƒÂ» no kodomo
26040,2020,2020 (Canceled) by,Mulan
26685,2020,Fall 2020 (Canceled) by,Greenland
26696,2020,2020 (Canceled) by,The Secret: Dare to Dream
27424,2021,July,Shika No Ou
28367,2021,2020 (Canceled) by,Stillwater
28381,2019,May,Fisherman's Friends
29082,2021,December,I Carry You With Me
29403,2021,Summer,Gyokou no Nikuko-chan
30319,2021,2022 (Canceled) by,El olvido que seremos
30410,2021,2021 (Canceled) by,Extinct
30555,2021,2021 (Canceled) by,Wish Dragon

In [111]:
sales["runtime_outlier"].value_counts()

runtime_outlier
False    30605
True         7
Name: count, dtype: int64

In [112]:
sales.loc[
    sales["runtime_outlier"] == True,
    [
        "title",
        "year",
        "runtime"
    ]
].sort_values(
    "runtime",
    ascending=False
)

                                      title  year  runtime
27957  Barbara Lee: Speaking Truth to Power  2021   2020.0
7179                               Amazonia  2015    983.0
16350                      AmÃ…Â¾inai kartu  2017    980.0
24691                               La Flor  2019    803.0
3431                           Meesterspion  2016    770.0
3427                 Out 1, noli me tangere  2015    760.0
28613                    The Works and Days  2021    480.0

In [113]:
financial_columns = [
    "international_box_office",
    "domestic_box_office",
    "worldwide_box_office",
    "production_budget",
    "opening_weekend"
]

sales[financial_columns].describe()

,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend
count,2.157500e+04,1.188400e+04,2.157500e+04,4.480000e+03,1.092900e+04
mean,1.586202e+07,1.735331e+07,2.524796e+07,3.642238e+07,5.488562e+06
std,6.659680e+07,5.050972e+07,1.009796e+08,4.644049e+07,1.633207e+07
min,2.000000e+00,2.000000e+01,2.000000e+00,1.100000e+03,1.100000e+01
25%,2.637500e+04,2.986550e+04,3.422900e+04,6.500000e+06,7.352000e+03
50%,3.348470e+05,2.587510e+05,4.753220e+05,2.000000e+07,4.087500e+04
75%,4.282312e+06,7.667212e+06,6.302152e+06,4.500000e+07,2.150979e+06
max,2.085392e+09,9.366622e+08,2.845900e+09,4.000000e+08,3.571150e+08

In [114]:
for column in financial_columns:
    print(
        column,
        (sales[column] < 0).sum()
    )

international_box_office 0
domestic_box_office 0
worldwide_box_office 0
production_budget 0
opening_weekend 0

In [115]:
sales["title"].isnull().sum()

np.int64(0)

In [116]:
sales.loc[
    sales["title"].isnull(),
    [
        "year",
        "release_date_original",
        "url"
    ]
]

Empty DataFrame
Columns: [year, release_date_original, url]
Index: []

In [117]:
sales["genre"].value_counts(dropna=False)

genre
Drama                  9218
Documentary            4683
Comedy                 4551
Thriller/Suspense      2281
Adventure              1999
Action                 1872
NaN                    1704
Horror                 1630
Romantic Comedy        1177
Concert/Performance     711
Musical                 268
Black Comedy            245
Multiple Genres         159
Western                 105
Educational               5
Reality                   4
Name: count, dtype: int64

In [118]:
# 1. Dataset size
print("Shape:", sales.shape)

# 2. Exact duplicate rows
print("Duplicate rows:", sales.duplicated().sum())

# 3. Unique primary key
print("sales_id unique:", sales["sales_id"].is_unique)
print("Missing sales_id:", sales["sales_id"].isnull().sum())

# 4. Missing values
print("\nMissing values:")
print(sales.isnull().sum())

# 5. Missing percentage
print("\nMissing percentage:")
print((sales.isnull().mean() * 100).round(2))

# 6. Negative financial values
financial_columns = [
    "international_box_office",
    "domestic_box_office",
    "worldwide_box_office",
    "production_budget",
    "opening_weekend"
]

print("\nNegative financial values:")
for col in financial_columns:
    print(col, (sales[col] < 0).sum())

# 7. Check date conversion problems
print(
    "\nUnclean release dates:",
    sales["release_date_clean"].isnull().sum()
)

# 8. Check flagged runtime outliers
print(
    "Runtime outliers:",
    sales["runtime_outlier"].sum()
)

# 9. Check encoding issues
print(
    "Possible encoding issues:",
    sales["encoding_issue"].sum()
)

# 10. Missing movie titles
print(
    "Missing titles:",
    sales["title"].isnull().sum()
)

Shape: (30612, 21)
Duplicate rows: 0
sales_id unique: True
Missing sales_id: 0

Missing values:
sales_id                        0
year                            0
release_date                    0
title                           0
genre                        1704
international_box_office     9037
domestic_box_office         18728
worldwide_box_office         9037
production_budget           26132
opening_weekend             19683
theatre_count               19649
avg_run_per_theatre         19660
runtime                      6053
keywords                    18103
creative_type                3945
url                             0
title_clean                     0
encoding_issue                  0
release_date_original           0
release_date_clean             46
runtime_outlier                 0
dtype: int64

Missing percentage:
sales_id                     0.00
year                         0.00
release_date                 0.00
title                        0.00
genre                        5.57
international_box_office    29.52
domestic_box_office         61.18
worldwide_box_office        29.52
production_budget           85.37
opening_weekend             64.30
theatre_count               64.19
avg_run_per_theatre         64.22
runtime                     19.77
keywords                    59.14
creative_type               12.89
url                          0.00
title_clean                  0.00
encoding_issue               0.00
release_date_original        0.00
release_date_clean           0.15
runtime_outlier              0.00
dtype: float64

Negative financial values:
international_box_office 0
domestic_box_office 0
worldwide_box_office 0
production_budget 0
opening_weekend 0

Unclean release dates: 46
Runtime outliers: 7
Possible encoding issues: 2636
Missing titles: 0

In [119]:
sales.loc[
    sales["runtime_outlier"] == True,
    ["sales_id", "title", "year", "runtime", "url"]
].sort_values("runtime", ascending=False)

,sales_id,title,year,runtime,url
27957,27958,Barbara Lee: Speaking Truth to Power,2021,2020.0,https://www.the-numbers.com/movie/Barbara-Lee-...
7179,7180,Amazonia,2015,983.0,https://www.the-numbers.com/movie/Amazonia-(Br...
16350,16351,AmÃ…Â¾inai kartu,2017,980.0,https://www.the-numbers.com/movie/Amzinai-kart...
24691,24692,La Flor,2019,803.0,https://www.the-numbers.com/movie/Flor-La-(Arg...
3431,3432,Meesterspion,2016,770.0,https://www.the-numbers.com/movie/Meesterspion...
3427,3428,"Out 1, noli me tangere",2015,760.0,https://www.the-numbers.com/movie/Out-1-noli-m...
28613,28614,The Works and Days,2021,480.0,https://www.the-numbers.com/movie/Works-and-Da...

In [120]:
sales["runtime_original"] = sales["runtime"]

In [121]:
sales["runtime_clean"] = sales["runtime"]

In [122]:
# Barbara Lee: Speaking Truth to Power
sales.loc[
    sales["sales_id"] == 27958,
    "runtime_clean"
] = 83

# Amžinai kartu
sales.loc[
    sales["sales_id"] == 16351,
    "runtime_clean"
] = 88

# Meesterspion
sales.loc[
    sales["sales_id"] == 3432,
    "runtime_clean"
] = 77

In [123]:
sales["runtime_status"] = "Normal"

sales.loc[
    sales["runtime_outlier"] == True,
    "runtime_status"
] = "Reviewed outlier"

sales.loc[
    sales["sales_id"].isin([27958, 16351, 3432]),
    "runtime_status"
] = "Corrected"

In [124]:
sales.loc[
    sales["runtime_outlier"] == True,
    [
        "sales_id",
        "title",
        "runtime_original",
        "runtime_clean",
        "runtime_status"
    ]
]

,sales_id,title,runtime_original,runtime_clean,runtime_status
3427,3428,"Out 1, noli me tangere",760.0,760.0,Reviewed outlier
3431,3432,Meesterspion,770.0,77.0,Corrected
7179,7180,Amazonia,983.0,983.0,Reviewed outlier
16350,16351,AmÃ…Â¾inai kartu,980.0,88.0,Corrected
24691,24692,La Flor,803.0,803.0,Reviewed outlier
27957,27958,Barbara Lee: Speaking Truth to Power,2020.0,83.0,Corrected
28613,28614,The Works and Days,480.0,480.0,Reviewed outlier

In [125]:
print("FINAL DATA QUALITY CHECK")
print("-------------------------")

print("Rows:", len(sales))
print("Columns:", len(sales.columns))
print("Duplicate rows:", sales.duplicated().sum())
print("Unique sales_id:", sales["sales_id"].is_unique)
print("Missing sales_id:", sales["sales_id"].isnull().sum())
print("Missing titles:", sales["title"].isnull().sum())
print("Missing URLs:", sales["url"].isnull().sum())

print("\nRelease dates not converted:",
      sales["release_date_clean"].isnull().sum())

print("Runtime outliers flagged:",
      sales["runtime_outlier"].sum())

print("Encoding issues flagged:",
      sales["encoding_issue"].sum())

FINAL DATA QUALITY CHECK
-------------------------
Rows: 30612
Columns: 24
Duplicate rows: 0
Unique sales_id: True
Missing sales_id: 0
Missing titles: 0
Missing URLs: 0

Release dates not converted: 46
Runtime outliers flagged: 7
Encoding issues flagged: 2636

In [126]:
sales.to_excel(
    "sales_cleaned_v1.xlsx",
    index=False
)

In [127]:
print("Saved successfully!")
print(sales.shape)

Saved successfully!
(30612, 24)

In [128]:
import os
print(os.getcwd())

c:\Users\user\Documents\UNI DDB